<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>project1</artifactId>
    <packaging>jar</packaging>
    <parent>
        <artifactId>sample.asciidoc</artifactId>
        <groupId>de.elnarion.sample</groupId>
        <relativePath>../pom.xml</relativePath>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>javax.persistence</groupId>
            <artifactId>javax.persistence-api</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>4.0.33</version>
            <type>pom</type>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>plantuml-generator-maven-plugin</artifactId>
                <groupId>de.elnarion.maven</groupId>
                <version>${plantumlgenerator.version}</version>
                <executions>
                    <execution>
                        <id>generate-simple-diagram</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-test-sources</phase>
                        <configuration>
                            <scanPackages>
                                <scanPackage>de.elnarion</scanPackage>
                            </scanPackages>
                            <additionalPlantUmlConfigs>
                                <additionalPlantUmlConfigs>left to right direction</additionalPlantUmlConfigs>
                            </additionalPlantUmlConfigs>
                            <outputFilename>testdiagram1.txt</outputFilename>
                            <whitelistRegexp>.*(Child|Student).*</whitelistRegexp>
                            <hideFields>true</hideFields>
                            <hideMethods>true</hideMethods>
                            <enableAsciidocWrapper>false</enableAsciidocWrapper>
                            <fieldClassifierListToIgnore>
                                <fieldClassifierListToIgnore>STATIC</fieldClassifierListToIgnore>
                            </fieldClassifierListToIgnore>
                            <maxVisibilityFields>PUBLIC</maxVisibilityFields>
                            <addJPAAnnotations>true</addJPAAnnotations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>3.0.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>addSources</goal>
                            <goal>addTestSources</goal>
                            <goal>generateStubs</goal>
                            <goal>compile</goal>
                            <goal>generateTestStubs</goal>
                            <goal>compileTests</goal>
                            <goal>removeStubs</goal>
                            <goal>removeTestStubs</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <!-- if including source jars, use the no-fork goals
                     otherwise both the Groovy sources and Java stub sources
                     will get included in your jar -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <!-- source plugin \> = 2.1 is required to use the no-fork goals -->
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                            <goal>test-jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>