<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>de.elnarion.sample</groupId>
	<artifactId>sample.asciidoc</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<java.version>11</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<asciidoctor.maven.plugin.version>2.2.6</asciidoctor.maven.plugin.version>
		<asciidoctorj.version>2.5.13</asciidoctorj.version>
		<asciidoclet.version>2.0.4</asciidoclet.version>
		<jruby.version>9.4.9.0</jruby.version>
		<docconverter.version>1.0.10</docconverter.version>
		<plantumlgenerator.version>2.4.1</plantumlgenerator.version>
		<asciidoc-extensions.version>1.0.3</asciidoc-extensions.version>
		<remoteplantuml>http://www.plantuml.com/plantuml/png/</remoteplantuml>
	</properties>

	<modules>
		<module>project1</module>
		<module>project2</module>
		<module>project3</module>
		<module>project4</module>
	</modules>

	<profiles>
		<profile>
			<id>asciidoc-generate</id>
			<activation>
				<file>
					<exists>${basedir}/.mvn/active-profiles/asciidoc-generate</exists>
				</file>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.asciidoctor</groupId>
						<artifactId>asciidoctor-maven-plugin</artifactId>
						<version>${asciidoctor.maven.plugin.version}</version>
						<dependencies>
							<!-- Comment this section to use the default jruby artifact provided 
								by the plugin -->
							<dependency>
								<groupId>org.jruby</groupId>
								<artifactId>jruby</artifactId>
								<version>${jruby.version}</version>
							</dependency>
							<!-- Comment this section to use the default AsciidoctorJ artifact 
								provided by the plugin -->
							<dependency>
								<groupId>org.asciidoctor</groupId>
								<artifactId>asciidoctorj</artifactId>
								<version>${asciidoctorj.version}</version>
							</dependency>
							<dependency>
								<groupId>de.elnarion.asciidoc</groupId>
								<artifactId>asciidoc-extension-multiinclude</artifactId>
								<version>${asciidoc-extensions.version}</version>
							</dependency>
							<dependency>
								<groupId>de.elnarion.asciidoc</groupId>
								<artifactId>asciidoc-extension-remoteplantuml</artifactId>
								<version>${asciidoc-extensions.version}</version>
							</dependency>
						</dependencies>
						<configuration>
							<sourceDirectory>src/main/asciidoc</sourceDirectory>
							<outputDirectory>target/docs/asciidoc</outputDirectory>
							<attributes>
								<remote_plantuml_url>${remoteplantuml}</remote_plantuml_url>
							</attributes>
						</configuration>
						<executions>
							<execution>
								<id>asciidoc-to-html</id>
								<phase>process-resources</phase>
								<goals>
									<goal>process-asciidoc</goal>
								</goals>
								<configuration>
									<backend>xhtml5</backend>
									<attributes>
										<source-highlighter>coderay</source-highlighter>
										<sectnums>true</sectnums>
										<linkcss>false</linkcss>
										<imagesdir>./images</imagesdir>
										<toc>left</toc>
										<icons>font</icons>
										<sectanchors>true</sectanchors>
										<idprefix />
										<idseparator>-</idseparator>
										<docinfo1>true</docinfo1>
									</attributes>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<artifactId>docconverter-maven-plugin</artifactId>
						<groupId>de.elnarion.maven</groupId>
						<version>${docconverter.version}</version>
						<executions>
							<execution>
								<id>html2pdf</id>
								<phase>prepare-package</phase>
								<goals>
									<goal>convert</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/docs/pdf</outputDirectory>
									<sourceDirectory>${basedir}/target/docs/asciidoc</sourceDirectory>
									<sourceMimeType>application/xhtml+xml</sourceMimeType>
									<targetMimeType>application/pdf</targetMimeType>
									<outputFileending>pdf</outputFileending>
									<sourceDocumentExtensions>html</sourceDocumentExtensions>
								</configuration>
							</execution>
						</executions>
						<dependencies>
							<dependency>
								<groupId>de.elnarion.util</groupId>
								<artifactId>docconverter-html2pdf</artifactId>
								<version>${docconverter.version}</version>
							</dependency>
						</dependencies>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>asciidoc-packaging</id>
			<activation>
				<file>
					<exists>${basedir}/.mvn/active-profiles/asciidoc-packaging</exists>
				</file>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>docconverter-maven-plugin</artifactId>
						<groupId>de.elnarion.maven</groupId>
						<version>${docconverter.version}</version>
						<executions>
							<execution>
								<id>adoc2adoc</id>
								<phase>prepare-package</phase>
								<goals>
									<goal>convert</goal>
								</goals>
								<configuration>
									<outputDirectory>${basedir}/target/adoc</outputDirectory>
									<sourceDirectory>${basedir}/src/main/asciidoc</sourceDirectory>
									<sourceMimeType>text/x.asciidoc</sourceMimeType>
									<targetMimeType>text/x.asciidoc</targetMimeType>
									<outputFileending>adoc</outputFileending>
									<sourceDocumentExtensions>adoc</sourceDocumentExtensions>
									<conversionParameters>
										<adoc2adoc.remain_include_statement_regexp>.*include\:\:\.\/.*\[\].*</adoc2adoc.remain_include_statement_regexp>
									</conversionParameters>
								</configuration>
							</execution>
						</executions>
						<dependencies>
							<dependency>
								<groupId>de.elnarion.util</groupId>
								<artifactId>docconverter-adoc2adoc</artifactId>
								<version>${docconverter.version}</version>
							</dependency>
						</dependencies>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-jar-plugin</artifactId>
						<version>3.5.1</version>
						<executions>
							<execution>
								<id>asciidoc-jar</id>
								<phase>package</phase>
								<goals>
									<goal>jar</goal>
								</goals>
								<configuration>
									<classifier>asciidoc</classifier>
									<classesDirectory>
										${basedir}/target/adoc
									</classesDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>asciidoc-unpackage</id>
			<activation>
				<file>
					<exists>${basedir}/.mvn/active-profiles/asciidoc-unpackage</exists>
				</file>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-dependency-plugin</artifactId>
						<version>3.8.1</version>
						<executions>
							<execution>
								<id>unpack</id>
								<phase>generate-resources</phase>
								<goals>
									<goal>unpack-dependencies</goal>
								</goals>
								<configuration>
									<includeClassifiers>asciidoc</includeClassifiers>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<release>${java.version}</release>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-toolchains-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<toolchains>
						<!-- this project needs a JDK toolchain, version 15 -->
						<jdk>
							<version>${java.version}</version>
						</jdk>
					</toolchains>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>toolchain</goal>
						</goals>
						<!-- the toolchain goal binds to the validate phase automatically -->
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>